### ISSUE TITLE
Treeform input data type

### ISSUE THREAD

**Issue by ZacZhangzhuo** [compas-dev/compas_viewer#57]
Hi @Licini @tomvanmele, I was a bit indecisive about the input data for the `Treeform` so I raised this issue for suggestions and discussion.

### pros
- It was used in the `view2`.
- might be universal.
### cons
- code duplicate to `compas.datastructrues.Tree`, such as: `def map_entries(self, entries, parent=None):` in [here](https://github.com/compas-dev/compas_view2/blob/07b86048346a18f83ff77c0209be1be8342b686e/src/compas_view2/forms/treeform.py#L120) is more or less Tree's child-parent hierarchy calculation.
- key names and dict format are fixed

### pros
- easy to make a treeform for the scene objects:
Ideally and primarily, it should be easy for users to create a `treefrom`  showing the existing objects in the renderer, which are `compas.scene.SceneTree`'s `compas.scene.SceneObjectNode`. the simplest dummy code should be like:
```python
sidedock= SidedockLayout()
sidedock.add(Treeform(viewer.tree))
viewer.add_sidedock(sidedock_layout)
```
- 
### cons
- looks like `Tree` in compas is just a data structure without any entities. We cannot attach any data/str/object to each `Node`?

---

currently, it looks like:
```python
class Treeform(QTreeWidget):
    """
    Class for displaying tree-like data.
    Treeform is an abstract class that could be placed in either the viewport or the sidedock.
    """

    def __init__(
        self,
        data: Tree,
        columns: list[str] = ["name", "value"], #any serializable attri or key can be the column
        column_editable: list[bool] = [False, False],
        show_headers: bool = True,
        striped_rows: bool = False,
    ):
```
shuttle to how it is in the `view2`: https://github.com/compas-dev/compas_view2/blob/main/src/compas_view2/forms/treeform.py

**Comment by petrasvestartas** [comment]
One suggestion we discussed to have several types:
a) a **tree** with a geometry specific attribute stored in kwargs
b) a **model** with its graph and tree
c) visualize a simple **dictionary** when iterating through it keys, values, when the attribute comes from  `compas.geometry` or `compas.datastructures` namespace it will be vizualized or "clickable".

**Comment by Licini** [comment]
After given some thoughts, how about you do this: 
Go for the `Tree` as input. In order to add additional attribute to a `TreeNode`, you should craete a new class from it for example `FormNode(TreeNode)` or `UINode(TreeNode)`. For dict inputs, you can simply extend the `Tree` class add a function to convert a dict to a tree.

Take a look from these examples for how to extend the tree class:
https://github.com/compas-dev/compas/blob/hashtree/src/compas/datastructures/tree/hashtree.py
https://github.com/compas-dev/compas/blob/18c1b465a00c3a0e104be10773412921aefaffc1/src/compas/scene/scene.py#L10
